flowchart TD
%% generated in 0.03s
    koru_autopilot_antigravity__src["koru-autopilot-antigravity.src<br/>203 funcs"]
    koru_autopilot_cursor__src["koru-autopilot-cursor.src<br/>118 funcs"]
    koru_autopilot_jetbrains__build["koru-autopilot-jetbrains.build<br/>4 funcs"]
    koru_autopilot_jetbrains__settings["koru-autopilot-jetbrains.settings<br/>2 funcs"]
    koru_autopilot_jetbrains__src["koru-autopilot-jetbrains.src<br/>8 funcs"]
    koru_autopilot_shared__src["koru-autopilot-shared.src<br/>299 funcs"]
    koru_autopilot_vscode__src["koru-autopilot-vscode.src<br/>69 funcs"]
    koru_autopilot_vscodium__src["koru-autopilot-vscodium.src<br/>125 funcs"]
    koru_autopilot_windsurf__src["koru-autopilot-windsurf.src<br/>59 funcs"]
