"""Preflight gates for autonomous / coru runs: runtime, daemon, plugin, socket."""

from __future__ import annotations

# Re-export all items from readiness module (including private functions for monkeypatch support)
from koru.autonomy.readiness.readiness import (  # noqa: F401
    ReadinessIssue,
    ReadinessResult,
    _TerminalLaneContext,
    _append_issue,
    _build_readiness_result,
    _canonical_target_ide,
    _check_daemon_meta_issues,
    _check_daemon_meta_project_python_issues,
    _check_daemon_version_issue,
    _check_plugin_workspace_issues,
    _check_socket_health_issues,
    _check_python_venv_alignment,
    _editable_install_fix,
    _effective_daemon_metadata,
    _find_project_in_workspace_folders,
    _first_fix_command,
    _installed_koru_version,
    _koru_runtime_identity_issue,
    _lane_ide_mismatch_issue,
    _lane_instance_value,
    _metadata_socket_matches,
    _package_version_drift_issue,
    _pid_alive,
    _planfile_availability_issue,
    _probe_planfile_version,
    _project_venv_koru,
    _project_venv_python,
    _project_venv_roots,
    _python_executable_mismatch_issue,
    _python_executables_equivalent,
    _runtime_issue_severity,
    _safe_path_for_compare,
    _socket_inode,
    _socket_lane_mismatch_issue,
    _status_daemon_metadata,
    _terminal_context,
    _terminal_lane_context,
    _terminal_lane_mismatch_issues,
    _venv_alignment_fix,
    _venv_alignment_issue,
    apply_socket_ownership_repairs,
    attempt_plugin_gate_recovery,
    check_daemon_client_alignment,
    check_lane_terminal_socket_alignment,
    check_queue_runner_contention,
    check_runtime_consistency,
    check_workspace_socket_ownership,
    daemon_status_compatible,
    detect_terminal_host_ide_id,
    evaluate_autonomous_readiness,
    format_readiness_lines,
    plugin_workspace_covers_project,
    probe_socket_health,
    run_plugin_reconnect_pipeline,
    warn_pre_drive_queue_without_plugin,
)




