flowchart TD
%% generated in 0.03s
    plugins__koru_autopilot_vscode["plugins.koru-autopilot-vscode<br/>128 funcs"]
    scripts___koru_autodiag_filter_tickets["scripts._koru_autodiag_filter_tickets<br/>1 funcs"]
    scripts__koru_gate_capture["scripts.koru-gate-capture<br/>14 funcs"]
    scripts__koru_soak_monitor["scripts.koru-soak-monitor<br/>6 funcs"]
    scripts__planfile_sync_todo["scripts.planfile-sync-todo<br/>9 funcs"]
    services__healing_webhook["services.healing-webhook<br/>34 funcs"]
    src__koru["src.koru<br/>723 funcs"]
    src__koruapi["src.koruapi<br/>86 funcs"]
    src__korudsl["src.korudsl<br/>26 funcs"]
    src__koruide["src.koruide<br/>164 funcs"]
    src__koru ==>|221| scripts__koru_soak_monitor
    src__koruapi ==>|42| src__koru
    src__koru ==>|33| src__koruide
    src__koruide ==>|26| scripts__koru_soak_monitor
    src__koruapi ==>|20| scripts__koru_soak_monitor
    scripts__planfile_sync_todo ==>|9| scripts__koru_soak_monitor
    src__koru ==>|5| plugins__koru_autopilot_vscode
    src__koru ==>|5| src__koruapi
    scripts__koru_gate_capture ==>|5| scripts__koru_soak_monitor
    src__koruapi ==>|4| src__korudsl
    src__koruide -->|3| src__koru
    services__healing_webhook -->|1| plugins__koru_autopilot_vscode
    scripts___koru_autodiag_filter_tickets -->|1| scripts__koru_soak_monitor
