# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dsl2koru/v1/command.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'dsl2koru/v1/command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64sl2koru/v1/command.proto\x12\x0b\x64sl2koru.v1\"G\n\x17QueryRepairHistoryQuery\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"5\n\x14QueryLaneStatusQuery\x12\x0b\n\x03ide\x18\x01 \x01(\t\x12\x10\n\x08instance\x18\x02 \x01(\t\"2\n\x11ValidateLaneQuery\x12\x0b\n\x03ide\x18\x01 \x01(\t\x12\x10\n\x08instance\x18\x02 \x01(\t\"/\n\x0cResolveQuery\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\"S\n\x10RepairRunCommand\x12\x0b\n\x03ide\x18\x01 \x01(\t\x12\x10\n\x08instance\x18\x02 \x01(\t\x12\x0f\n\x07project\x18\x03 \x01(\t\x12\x0f\n\x07trigger\x18\x04 \x01(\t\"\xf6\x02\n\x0b\x44slEnvelope\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x44\n\x14query_repair_history\x18\n \x01(\x0b\x32$.dsl2koru.v1.QueryRepairHistoryQueryH\x00\x12>\n\x11query_lane_status\x18\x0b \x01(\x0b\x32!.dsl2koru.v1.QueryLaneStatusQueryH\x00\x12\x37\n\rvalidate_lane\x18\x0c \x01(\x0b\x32\x1e.dsl2koru.v1.ValidateLaneQueryH\x00\x12,\n\x07resolve\x18\r \x01(\x0b\x32\x19.dsl2koru.v1.ResolveQueryH\x00\x12\x33\n\nrepair_run\x18\x0e \x01(\x0b\x32\x1d.dsl2koru.v1.RepairRunCommandH\x00\x12\x17\n\x0f\x64\x65\x66\x61ult_project\x18\x14 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x15 \x01(\tB\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dsl2koru.v1.command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREPAIRHISTORYQUERY']._serialized_start=42
  _globals['_QUERYREPAIRHISTORYQUERY']._serialized_end=113
  _globals['_QUERYLANESTATUSQUERY']._serialized_start=115
  _globals['_QUERYLANESTATUSQUERY']._serialized_end=168
  _globals['_VALIDATELANEQUERY']._serialized_start=170
  _globals['_VALIDATELANEQUERY']._serialized_end=220
  _globals['_RESOLVEQUERY']._serialized_start=222
  _globals['_RESOLVEQUERY']._serialized_end=269
  _globals['_REPAIRRUNCOMMAND']._serialized_start=271
  _globals['_REPAIRRUNCOMMAND']._serialized_end=354
  _globals['_DSLENVELOPE']._serialized_start=357
  _globals['_DSLENVELOPE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
