"""Prompts, redaction and promotion policy for patch tickets.

Letting an agent CLI edit files in place requires granting it write access to
the workspace — which in practice means disabling its permission prompts
wholesale. Patch mode avoids that trade: the agent only writes a unified diff
to stdout, and koru applies it. The diff is an inspectable, hashable artifact,
and git provides both the pre-flight check and the rollback path.

This module holds what koru *says* to the agent and what it *allows*. The
mechanics live next door: `diff_repair` normalises the reply, `workspace`
touches git and disk, `manifest` pins the plan. Those names are re-exported
here so callers have one import site.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path

from koru.proposal_envelope import NO_VALID_ARTIFACT
from koru.queue.diff_repair import extract_unified_diff, symlink_creations
from koru.queue.manifest import (
    MANIFEST_MISMATCH,
    MANIFEST_NOT_PERSISTED,
    build_manifest,
    load_persisted_manifest,
    manifest_drift,
    manifest_hash,
    persist_manifest,
    persisted_manifest_mismatch,
    workspace_snapshot_sha256,
)
from koru.queue.workspace import (
    apply_unified_diff,
    commit_on_main,
    commit_worktree,
    current_head,
    diff_target_files,
    dirty_paths,
    prune_stale_worktrees,
    repository_is_clean,
    revert_files,
    staging_worktree,
    worktree_enabled,
)

__all__ = [
    "MANIFEST_MISMATCH",
    "MANIFEST_NOT_PERSISTED",
    "apply_unified_diff",
    "build_manifest",
    "commit_on_main",
    "commit_worktree",
    "current_head",
    "diff_target_files",
    "dirty_paths",
    "extract_unified_diff",
    "manifest_drift",
    "manifest_hash",
    "load_persisted_manifest",
    "persist_manifest",
    "persisted_manifest_mismatch",
    "workspace_snapshot_sha256",
    "prune_stale_worktrees",
    "repository_is_clean",
    "revert_files",
    "staging_worktree",
    "symlink_creations",
    "worktree_enabled",
]

PATCH_PROMPT_SUFFIX = """

## Output contract

Do NOT edit any file. Emit your change as a single unified diff and nothing
else — no prose before or after it.

- Use `diff --git a/<path> b/<path>` headers with paths relative to the repository root.
- Follow each `diff --git` header with the `--- a/<path>` and `+++ b/<path>` lines.
- Every line inside a hunk MUST begin with a marker: a space for context, `-` for a
  removed line, `+` for an added one. A line starting at column 0 makes the whole
  patch unusable. Blank context lines are a single space, not an empty line.
- Changing a line means both a `-` line and a `+` line — never edit a line in place.
- Include at least 3 lines of context around every hunk so the patch applies cleanly.
- Emit one diff covering every file you change.
- If you cannot produce the change, emit exactly `NO-PATCH: <one-line reason>` instead.
"""




@dataclass(frozen=True)
class PatchOutcome:
    """Why a patch ticket failed, as data rather than prose.

    Callers and tests branch on ``code``; ``message`` exists only to be shown
    to a human. Keeping them separate stops behaviour from depending on
    wording that is expected to change.
    """

    code: str
    message: str
    retryable: bool = False
    workspace_left_untouched: bool = True
    diagnostics: str | None = None


# Failure codes. Mechanical ones may be regenerated by re-asking the agent;
# substantive and policy ones may not.
# Backward-compatible symbol for callers; the public structural code now names
# the actual contract failure rather than one particular missing output shape.
NO_PATCH_EMITTED = NO_VALID_ARTIFACT
PATCH_DOES_NOT_APPLY = "patch_does_not_apply"
UNSAFE_DIRTY_WORKSPACE = "unsafe_direct_apply_to_dirty_workspace"
PROMOTION_CONFLICT = "promotion_conflict"
VERIFY_FAILED_ISOLATED = "verify_failed_isolated"
VERIFY_FAILED_ROLLED_BACK = "verify_failed_rolled_back"
VERIFY_BASELINE_FAILED = "verify_baseline_failed"
VERIFY_PROFILE_INVALID = "verify_profile_invalid"
POLICY_DENIED = "policy_denied"


def patch_mode_enabled(ticket: dict) -> bool:
    """Whether this ticket's agent should propose a diff instead of editing.

    Explicit ``inputs.patch_mode`` wins; otherwise ``KORU_LLM_PATCH_MODE``
    decides, defaulting to on for edit tickets since it is the safer contract.
    """
    inputs = ticket.get("inputs") or {}
    if "patch_mode" in inputs:
        return bool(inputs["patch_mode"])
    raw = (os.environ.get("KORU_LLM_PATCH_MODE") or "").strip().lower()
    return raw not in {"0", "false", "no", "off"}


def build_patch_prompt(prompt: str) -> str:
    """Append the diff-only output contract to a ticket prompt."""
    return f"{prompt.rstrip()}\n{PATCH_PROMPT_SUFFIX}"


_SECRET_PATTERNS = (
    # Assignments: API_KEY=..., token: "...", password = '...'
    re.compile(
        r"(?i)\b([A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL)[A-Z0-9_]*)"
        r"(\s*[:=]\s*)(\"[^\"]*\"|'[^']*'|\S+)",
    ),
    # Bearer / Authorization headers.
    re.compile(r"(?i)\b(authorization|bearer)(\s*:?\s+)(\S+)"),
    # Recognisable standalone key shapes (sk-…, ghp_…, AKIA…, JWTs).
    re.compile(r"\b(sk-|ghp_|gho_|github_pat_|xox[baprs]-|AKIA)[A-Za-z0-9_\-]{8,}"),
    re.compile(r"\beyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]+"),
)

_REDACTED = "[redacted]"


def redact_secrets(text: str, *, limit: int = 2000) -> str:
    """Strip credential-shaped strings from output before it leaves the host.

    ``git`` and test runners echo file contents, so a diagnostic fed back to a
    model — or written into a ticket — can carry whatever the workspace holds.
    Redaction is deliberately over-eager: a mangled error message costs a retry,
    a leaked key costs far more.
    """
    if not text:
        return ""
    redacted = text
    for pattern in _SECRET_PATTERNS:
        if pattern.groups >= 3:
            redacted = pattern.sub(lambda m: f"{m.group(1)}{m.group(2)}{_REDACTED}", redacted)
        else:
            redacted = pattern.sub(_REDACTED, redacted)
    if len(redacted) > limit:
        redacted = redacted[:limit] + "\n… (truncated)"
    return redacted


def build_retry_prompt(prompt: str, failure: str) -> str:
    """Re-ask for a patch, quoting exactly why the previous one was rejected.

    ``git apply`` reports precisely what is wrong ("corrupt patch at line 8"),
    and that diagnostic is far more useful to the agent than a bare retry —
    without it the model tends to re-emit the same malformed diff.
    """
    return (
        f"{build_patch_prompt(prompt).rstrip()}\n\n"
        "## Previous attempt was rejected\n\n"
        f"Your last diff could not be applied:\n\n    {failure.strip()}\n\n"
        "Re-read the current contents of the files you are changing, then emit a "
        "corrected diff. Check that every hunk line starts with a space, `-` or `+`, "
        "that each changed line appears as both a `-` and a `+` line, and that the "
        "context lines match the file exactly as it is on disk right now."
    )


def current_file_excerpt(
    project: Path,
    paths: tuple[str, ...],
    *,
    max_chars: int = 6000,
) -> str:
    """Quote the files a patch must apply to, for a retry prompt.

    A context mismatch means the model's idea of the file is stale, and telling
    it so without showing the actual contents tends to produce the same diff
    again. Only safe once a manifest has pinned the base — otherwise this would
    hand the agent a snapshot that may already be out of date.
    """
    sections: list[str] = []
    budget = max_chars
    for rel in paths:
        target = project / rel
        if not target.is_file() or budget <= 0:
            continue
        try:
            raw = target.read_bytes()
        except OSError:
            continue
        if b"\x00" in raw[:8192]:
            # Binary. Quoting it would spend the budget on mojibake the model
            # cannot act on — it has no way to express a binary change as a
            # unified diff either. Name it and move on.
            sections.append(f"### `{rel}` — binary file, contents not shown")
            continue
        try:
            body = raw.decode("utf-8", errors="replace")
        except (UnicodeError, OSError):
            continue
        if len(body) > budget:
            body = body[:budget] + "\n… (truncated)"
        budget -= len(body)
        sections.append(f"### `{rel}` (current contents)\n\n```\n{redact_secrets(body, limit=budget + len(body))}\n```")
    if not sections:
        return ""
    return (
        "\n\n## The files as they are on disk right now\n\n"
        "Write your replacement diff against exactly this content.\n\n"
        + "\n\n".join(sections)
    )




















def symlinks_allowed() -> bool:
    """Whether agent patches may introduce symlinks (off by default)."""
    raw = (os.environ.get("KORU_QUEUE_ALLOW_SYMLINKS") or "").strip().lower()
    return raw in {"1", "true", "yes", "on"}






"""Where a verified patch is allowed to land."""
PROMOTION_APPLY = "apply"  # write into the workspace, leave committing to a human
PROMOTION_BRANCH = "branch"  # commit onto koru/run-<id>; workspace untouched
PROMOTION_COMMIT = "commit"  # apply and commit on the current branch
PROMOTION_ARTIFACT = "artifact"  # keep the patch as a file; change nothing

_PROMOTION_MODES = frozenset(
    {PROMOTION_APPLY, PROMOTION_BRANCH, PROMOTION_COMMIT, PROMOTION_ARTIFACT},
)

PROMOTION_REFUSED_DIRTY_REPO = "promotion_refused_dirty_repo"
PROMOTION_FAILED = "promotion_failed"
PATCH_INTRODUCES_SYMLINK = "patch_introduces_symlink"


def promotion_mode(ticket: dict) -> str:
    """How a verified patch should be delivered.

    Defaults to ``branch``: the result lands on its own ``koru/run-*`` ref, so
    a concurrent ``git add -A`` in another session cannot absorb it into an
    unrelated commit, and the shared working tree is never written to. ``apply``
    remains available explicitly for controlled local application.
    """
    raw = str((ticket.get("inputs") or {}).get("promotion_mode") or "").strip().lower()
    if raw in _PROMOTION_MODES:
        return raw
    env = (os.environ.get("KORU_QUEUE_PROMOTION_MODE") or "").strip().lower()
    return env if env in _PROMOTION_MODES else PROMOTION_BRANCH






def write_patch_artifact(project: Path, run_id: str, diff: str, evidence: dict) -> Path:
    """Persist the patch and its evidence without touching the workspace."""
    directory = project / ".koru" / "runs" / run_id
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "patch.diff").write_text(diff, encoding="utf-8")
    (directory / "evidence.json").write_text(
        json.dumps(evidence, indent=2, sort_keys=True), encoding="utf-8",
    )
    return directory



























