#!/usr/bin/env python3
"""Two-way sync between planfile.yaml and todo.md.

Design
------
`todo.md` is the **human** view — curated markdown checklist grouped by
area (Critical / High / Medium / Nice-to-have). `planfile.yaml` is the
**machine** view — structured tickets consumable by LLMs, CI, and the
healing-webhook.

This script keeps them in agreement:

  planfile → todo.md
    Every open ticket with label `llm-ready` is mirrored under the
    "## 🤖 Auto-generated (from planfile)" section of todo.md. If that
    section is missing it's appended at the bottom.

  todo.md → planfile
    Lines matching `- [ ] <text>` under "High Priority" (or a
    user-supplied heading) are imported as tickets with source=todo.md
    and label=imported-from-todo unless a matching ticket already
    exists (deduplicated by name).

Modes:
  --from-planfile     planfile → todo.md (default)
  --from-todo HEADING todo.md → planfile for the given H2/H3 heading
  --check             report diff without writing

The script is idempotent — re-running it on an already-synced tree is a
no-op.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TODO = REPO / "todo.md"
AUTO_HEADER = "## 🤖 Auto-generated (from planfile)"
AUTO_COMMENT = (
    "<!-- auto-generated by scripts/planfile-sync-todo.py — "
    "do not edit above the closing marker -->"
)
AUTO_END = "<!-- /auto-generated -->"


def run_planfile(*args: str) -> str:
    """Invoke the planfile CLI with stderr silenced (pydantic warnings pollute it)."""
    cmd = ["planfile", *args]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO, timeout=15)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"planfile {' '.join(args)} failed ({proc.returncode})")
    return proc.stdout


def load_tickets() -> list[dict]:
    """Prefer YAML because planfile's JSON mode can emit raw control chars in
    description blocks. PyYAML round-trips them correctly; json.loads chokes."""
    raw = run_planfile("ticket", "list", "--status", "all", "--format", "yaml")
    try:
        import yaml  # local import; only this script needs it
    except ImportError:  # pragma: no cover
        sys.stderr.write("PyYAML not installed; falling back to json (may lose tickets)\n")
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return []
    try:
        data = yaml.safe_load(raw) or []
        return data if isinstance(data, list) else []
    except Exception:
        return []


def build_auto_section(tickets: list[dict]) -> str:
    rows: list[str] = [AUTO_HEADER, "", AUTO_COMMENT, ""]
    grouped: dict[str, list[dict]] = {}
    for t in tickets:
        if "llm-ready" not in (t.get("labels") or []):
            continue
        if t.get("status") == "done":
            continue
        grouped.setdefault(t.get("priority", "normal"), []).append(t)

    for prio in ("critical", "high", "normal", "low"):
        items = grouped.get(prio, [])
        if not items:
            continue
        rows.append(f"### {prio.capitalize()}")
        rows.append("")
        for t in items:
            tid = t.get("id", "?")
            name = (t.get("name") or "").splitlines()[0][:100]
            rows.append(f"- [ ] **{tid}** — {name}")
        rows.append("")

    rows.append(AUTO_END)
    rows.append("")
    return "\n".join(rows)


def replace_auto_section(current: str, new_section: str) -> str:
    if AUTO_HEADER not in current:
        sep = "" if current.endswith("\n\n") else ("\n" if current.endswith("\n") else "\n\n")
        return current + sep + new_section
    # Replace from AUTO_HEADER to AUTO_END (inclusive).
    pattern = re.compile(
        rf"{re.escape(AUTO_HEADER)}.*?{re.escape(AUTO_END)}\n?",
        re.DOTALL,
    )
    return pattern.sub(new_section, current)


def do_from_planfile(check: bool) -> int:
    tickets = load_tickets()
    new_section = build_auto_section(tickets)
    current = TODO.read_text(encoding="utf-8") if TODO.exists() else ""
    updated = replace_auto_section(current, new_section)
    if updated == current:
        print("todo.md already in sync with planfile")
        return 0
    if check:
        print("todo.md would change (use without --check to write):")
        # Show a small diff summary, not the whole file.
        diff_lines = [ln for ln in updated.splitlines() if ln.startswith("- [ ] **PLF")]
        for ln in diff_lines[:10]:
            print("  +", ln)
        return 1
    TODO.write_text(updated, encoding="utf-8")
    print(f"wrote {TODO} ({len([t for t in tickets if 'llm-ready' in (t.get('labels') or [])])} llm-ready tickets)")
    return 0


def do_from_todo(heading: str, check: bool) -> int:
    if not TODO.exists():
        print("todo.md not found; nothing to import", file=sys.stderr)
        return 2
    text = TODO.read_text(encoding="utf-8")
    # Grab everything under `## <heading>` or `### <heading>` until the next heading of equal/higher level.
    pattern = re.compile(
        rf"^(#{2,3})\s+{re.escape(heading)}\s*$(.*?)(?=^\1\s|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        print(f"heading '{heading}' not found in todo.md", file=sys.stderr)
        return 2
    body = match.group(2)
    items = re.findall(r"^\s*-\s*\[ \]\s+(.+?)\s*$", body, re.MULTILINE)
    if not items:
        print("no open items under that heading")
        return 0

    existing_names = {t.get("name") or "" for t in load_tickets()}
    created: list[str] = []
    for item in items:
        name = f"[todo.md] {item}"
        if any(name in n for n in existing_names):
            continue
        if check:
            created.append(name)
            continue
        run_planfile(
            "ticket",
            "create",
            name,
            "--priority",
            "normal",
            "--source",
            "todo.md",
            "--label",
            "imported-from-todo",
            "--label",
            "llm-ready",
            "--description",
            _llm_stub(item, heading),
        )
        created.append(name)
    action = "would create" if check else "created"
    print(f"{action} {len(created)} ticket(s)")
    for n in created[:10]:
        print("  -", n)
    return 0


def _llm_stub(item: str, heading: str) -> str:
    return (
        f"## 🚨 Context\n\n- **Source:** todo.md → {heading}\n- **Task:** {item}\n\n"
        "## 🔁 Reproduction\n\n(Task doesn't have a reproduction yet — document it "
        "before starting.)\n\n## ✅ Acceptance criteria\n\n- [ ] Task satisfied per "
        "its description\n- [ ] No new regression in `task test`\n- [ ] `redsl gate "
        "check` passes\n\n## 🔒 Constraints\n\n- Keep the diff minimal and focused "
        "on this item.\n- If scope balloons, split into multiple tickets.\n\n"
        "## 🤖 Prompt (LLM-agnostic)\n\n> Work the task described above. Use the "
        "c2004 Taskfile and redsl.yaml gates for validation.\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    grp = ap.add_mutually_exclusive_group()
    grp.add_argument("--from-planfile", action="store_true", help="sync tickets → todo.md (default)")
    grp.add_argument("--from-todo", metavar="HEADING", help="import items under an H2/H3 heading")
    ap.add_argument("--check", action="store_true", help="don't write, report diff only")
    args = ap.parse_args()

    if args.from_todo:
        return do_from_todo(args.from_todo, args.check)
    return do_from_planfile(args.check)


if __name__ == "__main__":
    sys.exit(main())
